### ISSUE TITLE
Validate using data with different resolutions

### ISSUE THREAD

**Issue by dongyyyy** [prs-eth/Marigold#109]
My training data and verification data are images with different resolutions, but there is a problem of dimension mismatch during verification. I don't know how to solve this problem.My data is read with the following Settings：
resize_to_hw:
    - 480
    - 640
    
<img width="737" alt="Q" src="https://github.com/user-attachments/assets/70a86865-42c6-41a4-bed8-e04528e20f19">
thank you.

**Comment by markkua** [comment]
Hi, if the input size is not the factorial of 2, the output size could be at a slightly different shape, due to the convolutional process in the UNet. You can do padding or cropping to avoid this, like [here](https://github.com/huggingface/diffusers/blob/e780c05cc3e7816dca976622ef03bc734c486866/src/diffusers/pipelines/marigold/pipeline_marigold_depth.py#L471).
