### ISSUE TITLE
Maxing out VRAM at 24GB

### ISSUE THREAD

**Issue by danganbenpa** [prs-eth/Marigold#14]
I was told that Marigold maxing out my 24gb VRAM isn't supposed to happen and was told to post my settings here.

I have a bat file that I run with the following:

@echo off
call venv/marigold/Scripts/activate.bat
python run.py --checkpoint checkpoint/Marigold_v1_merged --input_rgb_dir Input --output_dir Output
pause

**Comment by markkua** [comment]
Hello, thanks for reporting the issue. This is not supposed to happen since the command you used would automatically resize the input image and will only use <10G VRAM. 
Could you provide more information about:
- System
- GPU model
- Cuda version
- Python version
- requirements.txt, by running ’pip freeze > requirements.txt’
- if possible, could you also provide the image that failed. 
These would be helpful for us to spot the problem. 
Best.
