### ISSUE TITLE
Can Marigold be used as segmentation?

### ISSUE THREAD

**Issue by adkAurora** [prs-eth/Marigold#23]
Awesome Work~ 
The foreground effect of the depth estimation is very good, even better than SAM ，Have you considered applying it to the field of saliency detection?
![image (5)](https://github.com/prs-eth/Marigold/assets/30972697/d8797069-3e18-45ba-8baf-adc8ac1f20a3)

**Comment by toshas** [comment]
Thanks for your interest! You might be onto something, but it is not immediately clear to me how you propose to separate the foreground. In your example, the floor area at the very bottom is closer to the camera than the bench pixels, which is why naive thresholding won't work. Also, I see no simple way to perform connected components analysis, as the bottom of the bench legs has the same depth values as the floor underneath. All in all, this calls for some learned approach. I will close the ticket for now, but feel free to continue the discussion in this ticket -- we are always on the lookout for cool applications!

**Comment by Darkbblue** [comment]
> Thanks for your interest! You might be onto something, but it is not immediately clear to me how you propose to separate the foreground. In your example, the floor area at the very bottom is closer to the camera than the bench pixels, which is why naive thresholding won't work. Also, I see no simple way to perform connected components analysis, as the bottom of the bench legs has the same depth values as the floor underneath. All in all, this calls for some learned approach. I will close the ticket for now, but feel free to continue the discussion in this ticket -- we are always on the lookout for cool applications!

Maybe consider fine-tuning a new model specifically for other discriminative tasks? I see no direct obstacles preventing such generalization of your methodology. There are previous studies that train diffusion models from scratches for segmentation or depth estimation, and Marigold essentially extends this schema to fine-tuning a general-purpose SDv1.5 instead. So it makes sense to train new Marigold models for other tasks.
