### ISSUE TITLE
"--seed" not making results reproducible

### ISSUE THREAD

**Issue by petermg** [prs-eth/Marigold#32]
I did a test, duplicated a jpeg in a directory, so there's just 2 image files, same file just different names. I ran this with the --seed and each image was different. It seems a random seed is being generated for each image regardless of this argument. So specifying a seed does NOT make the results reproducible.

**Comment by markkua** [comment]
Hello, the random seed is only set once at the beginning of inference, it's designed to reproduce results when you run the script on the same data multiple times.  So in your case, if you run inference once, copy out the prediction, and run again, they should be almost the same (due to computational error, they might not be 100% the same).
