### ISSUE TITLE
About some problems that arise during training

### ISSUE THREAD

**Issue by water221** [prs-eth/Marigold#95]
![image](https://github.com/prs-eth/Marigold/assets/52553731/ef4012be-c523-4814-8a2b-dd8b8400d9f1)
My system is Ubantu 20.04.1, and the training environment is GeForce RTX3090, python 3.10, CUDA=11.7. I used the command ```python train.py--config config/train_marigold.yaml --no_wandb ```to start the project and it has been stuck here without any follow-up actions and no log output. Does anyone know where the problem is? Can you help solve it? In addition, I use Hypersim and vkitti datasets

**Comment by water221** [comment]
![image](https://github.com/prs-eth/Marigold/assets/52553731/ce46dee4-6259-402d-aef6-60054441f17c)
Supplement:Only the above log output, and then there is no other output or action

**Comment by YacineDeghaies** [comment]
Did you use Conda for the dependencies or pip ?

**Comment by water221** [comment]
> Did you use Conda for the dependencies or pip ?

Yes, I am using the dependency environment for conda installation. After investigation, I now feel that the dataset has not been downloaded completely. I wonder if anyone can answer whether the evaluation dataset also needs to be downloaded completely?

**Comment by YacineDeghaies** [comment]
Can you please share your dependencies for training ? I'm also doing the same trying to train it.

**Comment by water221** [comment]
> Can you please share your dependencies for training ? I'm also doing the same trying to train it.

You can find the dependencies you want in the three files: requirements.txt, requirements+.txt and requirements++.txt. I installed them using the pip command

**Comment by YacineDeghaies** [comment]
Where you able to train the model ?

**Comment by water221** [comment]
> Where you able to train the model ?

On my server

**Comment by YacineDeghaies** [comment]
培训对你有用吗？

**Comment by water221** [comment]
> 培训对你有用吗？

of course

**Comment by markkua** [comment]
I have never encountered this. Some people found the uncompressed tar file to be the obstacle https://github.com/prs-eth/Marigold/issues/94.

**Comment by water221** [comment]
Thank you very much, I'll take a look

**Comment by zad37** [comment]
> ![image](https://private-user-images.githubusercontent.com/52553731/345846698-ef4012be-c523-4814-8a2b-dd8b8400d9f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDA1MTEsIm5iZiI6MTcyOTMwMDIxMSwicGF0aCI6Ii81MjU1MzczMS8zNDU4NDY2OTgtZWY0MDEyYmUtYzUyMy00ODE0LThhMmItZGQ4Yjg0MDBkOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAxMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlN2ZjYzM3NDU5OTdlYWQyYjFiYmRlOWNjZDc1ZTk1YmY0MzRhMDA3MjQ3Yjc2OGQ0NjM1N2M1MjJkODJlOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.28llCtA7ZCb7SZyCXip3hG5nFvv7MSlCwUx3wXsqlDQ)我的系统是 Ubantu 20.04.1，训练环境是 GeForce RTX3090，python 3.10，CUDA=11.7。我使用命令启动项目，但它一直卡在这里，没有任何后续操作，也没有日志输出。有谁知道问题出在哪里？您能帮忙解决吗？此外，我还使用 Hypersim 和 vkitti 数据集`python train.py--config config/train_marigold.yaml --no_wandb `
Hello, I'm facing the same issue as you, have you found a solution?

**Comment by zad37** [comment]
Hello, I'm facing the same issue as you, have you found a solution?

**Comment by u-can-u-up-no-bb** [comment]
Hi,
You might try to train without tar, I.e. simply untar your folders and change the data config, pointing it to the untarred folder.

On 18 Oct 2024, at 21:11, zad37 ***@***.***> wrote:

﻿

Hello, I'm facing the same issue as you, have you found a solution?

**Comment by zad37** [comment]
Hello, thank you for your answer, I think I found the problem. This is a somewhat magical problem that I have not yet figured out how to solve, and I hope you can provide some suggestions.


2024-10-19 09:49:55,811 - INFO -train.py - <module&gt; &gt;&gt; Code snapshot saved to: ./output/train_marigold/code_snapshot.tar


As I watched the code run, I noticed that the code_snapshot.tar file was taking up an ever-increasing amount of memory that seemed to never end. This file appears to be a copy of the original file, but that file contains an ever-expanding version of itself, which can never be copied, eventually resulting in an infinitely larger effect, so that the training program can not be stuck and the master can not continue to run. I would like to know if you have encountered such problems in the run, how the file structure is, and the idea of solving this problem. thank you.




雨夜的旅行者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "prs-eth/Marigold"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月19日(星期六) 上午9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [prs-eth/Marigold] About some problems that arise during training (Issue #95)





 Hi, 
 You might try to train without tar, I.e. simply untar your folders and change the data config, pointing it to the untarred folder. 
 
 On 18 Oct 2024, at 21:11, zad37 ***@***.***&gt; wrote: 
 
 ﻿ 
 
 Hello, I'm facing the same issue as you, have you found a solution?

**Comment by zad37** [comment]
I solved this problem by making the following changes:

os.system(
f"rsync --relative -arhvz --quiet --filter=':- .gitignore' --exclude '.git' --exclude 'code_snapshot.tar' . '{_temp_code_dir}'"
)

But then came a new mistake:

Traceback (most recent call last):
File "/root/Marigold/train.py", line 266, in
assert len(cfg_data.train.prob_ls) == len(

I think these two problems are related, because I once caused this error due to insufficient memory caused by the first error, which made me very confused, I hope to get some help and advice, thank you.

**Comment by zad37** [comment]
The problem has been solved, thank you.
